### ISSUE TITLE
 Needs a screenshot

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.gnu.emacs#1]
This app needs one or more screenshots added to the appdata

**Comment by zoglesby** [comment]
This *should* be fixed once https://github.com/flathub/org.gnu.emacs/pull/3 is merged, I verified that that appdata.xml has a screenshot in it

**Comment by muep** [comment]
Also the old metadata has a screenshot link included, but it seems to have been marked in a way that is not understood by the flathub web page. Hopefully this new metadata from Emacs 26.1 is more compatible.

**Comment by muep** [comment]
It seems that metadata from Emacs 26.1 is not getting loaded into the web page at all. I opened an [issue](https://github.com/flathub/flathub/issues/410) to flathub/flathub because I have no idea about how to troubleshoot this, apart from blindly publishing changes to the appdata xml.

**Comment by muep** [comment]
Now the metadata is getting loaded but still no screenshot. Will need to study this more.

**Comment by nedrichards** [comment]
I wouldn't be at all surprised if the issue wasn't the same as this one in uberwriter: https://github.com/flathub/de.wolfvollprecht.UberWriter/issues/2 where, the 16:9 crop of the image came in under the minimum size for the screenshot. There's instructions on debugging etc. in that thread.

**Comment by muep** [comment]
Now the screenshot is visible at https://flathub.org/apps/details/org.gnu.emacs
