### ISSUE TITLE
On Debian, emacs ends up running as the root user

### ISSUE THREAD

**Issue by michel-slm** [flathub/org.gnu.emacs#11]
On Debian testing (MATE desktop), when I run the Emacs installed from flatpak it's running as root:
![screenshot from 2018-08-29 17-53-17](https://user-images.githubusercontent.com/85603/44823303-8940fa00-abb4-11e8-8052-920d7a12a891.png)

On Fedora, both `bwrap` processes run as my normal user:
```
~
$ ps auxwww | grep emacs
michel    7462  0.2  0.0  17600  1232 pts/3    S+   17:51   0:00 bwrap --args 18 emacs
michel    7473  0.2  0.0  17996  1704 pts/3    S+   17:51   0:00 bwrap --args 18 emacs
michel    7474 15.4  0.3 579964 125752 pts/3   Sl+  17:51   0:02 emacs
michel    7573  0.0  0.0 213800  1064 pts/11   S+   17:51   0:00 grep --color=auto emacs
```

Debian:
```
dpkg -s flatpak | grep Version
Version: 1.0.0-1
```

Fedora:
```
rpm -q flatpak
flatpak-1.0.0-2.fc28.x86_64
```

**Comment by nedrichards** [comment]
This is a bubblewrap issue: https://github.com/projectatomic/bubblewrap if your distribution doesn't allow unprivelaged user namespaces then the sandbox helper necessarily needs to be SUID.

This isn't emacs specific so I'm going to close it here but feel free to talk more about security over at bubblewrap and flatpak https://github.com/flatpak/flatpak

**Comment by TingPing** [comment]
It is MATEs issue really: https://github.com/mate-desktop/marco/issues/301
