### ISSUE TITLE
Request for beta-pgtk branch creation (i have the code ready for PR)

### ISSUE THREAD

**Issue by jistr** [flathub/org.gnu.emacs#33]
Hello,

i'd like to request creation of `beta-pgtk` branch. There is a `feature/pgtk` branch [1] in GNU's Emacs git repo, which contains "pure GTK3" port of Emacs. It is intended to land in master eventually, but it hasn't yet.

The current Emacs flatpak is barely usable with Wayland on high-DPI screens with non-integer (fractional) scaling factors, as the text is rendered blurry. The pgtk branch fixes that - rendering on Wayland with fractional scaling is crisp. For me, and i expect for some others too, this is currently the only reasonable way to run graphical Emacs.

If and when the branch is created, i will submit a PR with code for it. I've tested it locally [2].

[1] https://git.savannah.gnu.org/cgit/emacs.git/log/?h=feature/pgtk 
[2] https://github.com/jistr/org.gnu.emacs/commit/de07b399d473e5840d1fcb43ab5a64c0bc4bd5a5

**Comment by muep** [comment]
@jistr I pushed the branch, should be identical to the current master branch. Does it seem OK to you?

**Comment by jistr** [comment]
@muep Yes all ok, thanks! I've created the pull request against the branch. https://github.com/flathub/org.gnu.emacs/pull/34
