### ISSUE TITLE
Please build with native JSON parsing support

### ISSUE THREAD

**Issue by bk138** [flathub/org.gnu.emacs#35]
https://github.com/emacs-mirror/emacs/blob/master/etc/NEWS.27#L93 has some info on this. This probably means that this flatpak has to build and include libjansson.

**Comment by manuq** [comment]
Yep since the default is [`--with-json=ifavailable`](https://github.com/emacs-mirror/emacs/blob/138486cddb9a0a4e3f159a6e9d7711570bdf2a4c/configure.ac#L456), building libjansson would do it.
