### ISSUE TITLE
Unofficial Flatpak version of GNU Emacs

### ISSUE THREAD

**Issue by nizish** [flathub/org.gnu.emacs#39]
This is the warning I get the first time I run emacs.

> https://www.flathub.org
> 
> ------------------------------------------------------------------------------------
> | Warning: You are running an unofficial Flatpak version of GNU Emacs !!! |
> ------------------------------------------------------------------------------------
> 
> Please open issues under: https://github.com/flathub/org.gnu.emacs/issues
> 
> 
> This version is running inside a container and is therefore not able
> to access SDKs on your host system!
> 
> This flatpak provides a standard development environment (gcc, python, etc).
> To see what's available:
> 
>   $ flatpak run --command=sh org.gnu.emacs
>   $ ls /usr/bin (shared runtime)
>   $ ls /app/bin (bundled with this flatpak)
> 
> To get support for additional languages, you have to install SDK extensions, e.g.
> 
>   $ flatpak install flathub org.freedesktop.Sdk.Extension.dotnet
>   $ flatpak install flathub org.freedesktop.Sdk.Extension.golang
>   $ FLATPAK_ENABLE_SDK_EXT=dotnet,golang flatpak run org.gnu.emacs
> 
> You can use
> 
>   $ flatpak search <TEXT>
> 
> to find others.
>

**Comment by muep** [comment]
This is warning intentionally shipped in the flatpak distribution, to make users aware of some ways in which the Flatpak-packaged Emacs differs from an usual one.
