### ISSUE TITLE
Some builds failing

### ISSUE THREAD

**Issue by zoglesby** [flathub/org.gnu.emacs#4]
Only one build seems to pass each run, after my commit it was the i386 build, the most resent comment seems to be the aarch64 build.

https://flathub.org/builds/#/builders/2/builds/1908
https://flathub.org/builds/#/builders/2/builds/1909

**Comment by zoglesby** [comment]
Note, that it seems to be caused by the fact that it can't find the source tarball on the flathub mirror.

**Comment by zoglesby** [comment]
`Downloading sources
]2;flatpak-builder: Downloading emacsDownloading http://ftpmirror.gnu.org/emacs/emacs-26.1.tar.xz
Trying mirror https://dl.flathub.org/repo/downloads/1cf4fc240cd77c25309d15e18593789c8dbfba5c2b44d8f77c886542300fd32c/emacs-26.1.tar.xz
Failed to download sources: module emacs: Not Found`

**Comment by muep** [comment]
https://github.com/flathub/org.gnu.emacs/pull/5 addresses this with a workaround

**Comment by zoglesby** [comment]
https://github.com/flathub/org.gnu.emacs/pull/5 fixed the issue.
