### ISSUE TITLE
Fails to launch

### ISSUE THREAD

**Issue by philn** [flathub/org.gnu.emacs#52]
```
$ flatpak run org.gnu.emacs
emacs-wrapper-wrapper: Setting up NPM packages
emacs-wrapper-wrapper: Setting up Cargo packages
emacs-wrapper-wrapper: Setting up Python packages
/app/bin/emacs-wrapper: line 111: touch: command not found
```

**Comment by philn** [comment]
`/bin` is missing in PATH

**Comment by muep** [comment]
In the runtime, `/bin` is a symlink to `/usr/bin` which in turn is included in `PATH`.

Emacs started by `flatpak run org.gnu.emacs` does run for me if I start it with latest updates in place. Is there something uncommon about the system where you wish to run it?

**Comment by philn** [comment]
I'm on Fedora Silverblue 36, I have rustup set-up on the host though, and that's what messing up my PATH somehow. Sorry for the noise!
